/** Data contracts for the v2 SQLite-backed dashboard API */

// Re-export UI types from shared package
// Re-export dashboard contract types from shared package
export type {
  EvalSnapshot,
  EvidenceEntry,
  EvolutionEntry,
  OrchestrateRunReport,
  OrchestrateRunSkillAction,
  PendingProposal,
  SkillCard,
  SkillHealthStatus,
  UnmatchedQuery,
} from "@selftune/ui/types";

// Types that remain local (only used by pages/hooks, not by shared components)
export type {
  AnalyticsResponse,
  CreatorOverviewStep,
  CreatorLoopNextStep,
  CreatorTestingOverview,
  AttentionCategory,
  AttentionItem,
  AutonomousDecision,
  AutonomyStatus,
  AutonomyStatusLevel,
  CanonicalInvocation,
  CommitRecord,
  CommitSummary,
  DashboardActionEvent,
  DashboardActionMetrics,
  DashboardActionEventStage,
  DashboardActionName,
  DashboardActionProgress,
  DashboardActionResultSummary,
  DashboardFrontierMember,
  DashboardFrontierState,
  DashboardSearchProvenance,
  DashboardSearchRunSummary,
  DashboardSearchRunView,
  DecisionKind,
  DoctorResult,
  ExampleRow,
  ExecutionMetrics,
  HealthCheck,
  HealthResponse,
  HealthStatus,
  OrchestrateRunsResponse,
  OverviewPaginatedPayload,
  OverviewPayload,
  OverviewResponse,
  PaginatedResult,
  PaginationCursor,
  PromptSample,
  RecentActivityItem,
  SessionMeta,
  SkillReportPaginatedPayload,
  SkillReportPayload,
  SkillReportResponse,
  SkillTestingReadiness,
  SkillSummary,
  SkillUsageRecord,
  TelemetryRecord,
  TrustBucket,
  TrustFields,
  TrustState,
  TrustWatchlistEntry,
} from "../../../cli/selftune/dashboard-contract";

export type { CreateCheckReadiness, CreateCheckState } from "../../../cli/selftune/types";
